Model dir= experiments/simple_rnn_kt/h_dim__lr_0.005_decay_0.9_batch_1024_epochs_30_hidden_320_Njets_40000_features_7
CUDA_VISIBLE_DEVICES=2 /opt/anaconda3/bin/python train.py --model_dir=experiments/simple_rnn_kt/h_dim__lr_0.005_decay_0.9_batch_1024_epochs_30_hidden_320_Njets_40000_features_7 --data_dir=../data/inputTrees/top_qcd_jets_antikt_antikt
Traceback (most recent call last):
  File "search_hyperparams.py", line 150, in <module>
    multi_scan(learning_rates=[5e-3],decays=[0.9], batch_sizes=[1024],num_epochs=[30],hidden_dims=[320,640],jet_numbers=[40000],dir_name='simple_rnn_kt',name='h_dim_')#gpu2
  File "search_hyperparams.py", line 113, in multi_scan
    launch_training_job(parent_dir, args.data_dir, args.eval_data_dir, job_name, params, args.gpu)        
  File "search_hyperparams.py", line 45, in launch_training_job
    check_call(cmd_train, shell=False)
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'CUDA_VISIBLE_DEVICES=2 /opt/anaconda3/bin/python train.py --model_dir=experiments/simple_rnn_kt/h_dim__lr_0.005_decay_0.9_batch_1024_epochs_30_hidden_320_Njets_40000_features_7 --data_dir=../data/inputTrees/top_qcd_jets_antikt_antikt': 'CUDA_VISIBLE_DEVICES=2 /opt/anaconda3/bin/python train.py --model_dir=experiments/simple_rnn_kt/h_dim__lr_0.005_decay_0.9_batch_1024_epochs_30_hidden_320_Njets_40000_features_7 --data_dir=../data/inputTrees/top_qcd_jets_antikt_antikt'
